version: '3.7'

networks:
  webapp-prod:
    driver: bridge

services:
  webapp:
    image: alicoskun/webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - "webapp-prod"
    ports:
      - "8083:80"
    depends_on:
      - "appdb"
  
  appdb:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=bloguser"
      - "POSTGRES_PASSWORD=bloguser"
      - "POSTGRES_DB=blogdb"
    restart: always
    ports:
      - "7000:5432"
    networks:
      - "webapp-prod"